### ISSUE TITLE
how to use text variables? Virtuino 6

### ISSUE THREAD

**Issue by uzi18** [iliaslamprou/virtuinoCM#4]
Hi @iliaslamprou 
Trying to understand how connect everything between app and sketch together.
Could you please explain how to show Text values (assigned in sketch) in android application text widget? 
What widget is intended to use for such scenario?

**Comment by iliaslmp** [comment]
Hi, this is an example of the arduino code: https://virtuino.com/downloads/examples/virtuinoCM/Wemos_NodeMCU_ESP8266_Vmemory_text.zip
The library examples format the Vpins as float values.
For text values you have to declare some of the Vpins as String. 
On Virtuino panel just add a "Text Value Display". Select the V pin than contains the text.
I hope the code example to help you

**Comment by uzi18** [comment]
Thank you, will check this out.

**Comment by uzi18** [comment]
```
 * The 'variableType' can be a character like V, T, O  V=Virtual pin  T=Text Pin    O=PWM Pin 
 * 
```

So have misunderstood this line, fought need Text pin in application.

**Comment by uzi18** [comment]
@iliaslmp what if i want to edit this text in widget is it possible?

**Comment by iliaslmp** [comment]
Virtuino 6 uses the V pins for any type of variables (text and numbers).
In the version 5 is used the T pin for the text values. The library supports projects from both version 5 and 6.
Open the settings window of the "Text Value Display". Click the tab "More".
At the bottom select the action "Show dialog to edit value"
The other way is to create a "Popup text editor". You can call this using a "System button".
This video will help you with the "popups"  https://youtu.be/X7g59oljyNs

**Comment by uzi18** [comment]
@iliaslmp thanks for the clarification
